version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      -  DATABASE_URL= "host=localhost user=postgres password=postgres dbname=gophers sslmode=disable" 
      -  DATABASE_URL_DEV= "host=localhost user=postgres password=postgres dbname=gophers sslmode=disable" 
      -  SERVER_PORT="8080"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gophers
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
